# Generated by Django 5.1.5 on 2025-02-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_particpants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
