# Generated by Django 5.1.5 on 2025-02-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='particpants',
            new_name='participants',
        ),
    ]
